### ISSUE TITLE
Wrong variable name in create gninatypes types script

### ISSUE THREAD

**Issue by liuzh47** [fimrie/DEVELOP#2]
The `create_gninatypes_and_types_files.sh` script has an error for variable name. See https://github.com/fimrie/DEVELOP/blob/main/data/create_gninatypes_and_types_files.sh#L14

The `smiInput` is not defined before, it should be changed to `basePath` instead.

**Comment by fimrie** [comment]
Thank you! I've updated the repo accordingly.
