### ISSUE TITLE
Examples/DEVELOP_elaboraton_example.ipynb is not working

### ISSUE THREAD

**Issue by ChengchengGutenTag** [fimrie/DEVELOP#3]
Dear all,

I was trying to run the example file "DEVELOP_elaboraton_example.ipynb" but it turns out to have errors as below. Do you also have this issue?

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-20-3e7986d03c2a> in <module>
      1 # Setup model and generate molecules
      2 model = DenseGGNNChemModel(args)
----> 3 model.train()
      4 # Free up some memory
      5 model = ''

/data3/fancc/DEVELOP/GGNN_DEVELOP.py in train(self)
    382                 # Run epoches for graph generation
    383                 if epoch >= self.params['epoch_to_generate']:
--> 384                     self.generate_new_graphs(self.valid_data, self.valid_struct_data)
    385                     break
    386 

/data3/fancc/DEVELOP/DEVELOP.py in generate_new_graphs(self, data, struct_data)
   1189                                                          self.params['hidden_size']) # [1, v, h]  
   1190                     self.generate_graph_with_state(random_normal_states, random_normal_states_in,
-> 1191                                        maximum_length, generated_all_smiles, elements, count, cnn_input)
   1192                     count+=1
   1193             bucket_counters[bucket] += 1

/data3/fancc/DEVELOP/DEVELOP.py in generate_graph_with_state(self, random_normal_states, random_normal_states_in, num_vertices, generated_all_smiles, elements, count, cnn_input)
   1056                                      random_normal_states, random_normal_states_in, 0, cnn_input)
   1057         # Get predicted node probs (symbol and keep)
-> 1058         predicted_node_symbol_prob = self.get_node_symbol(node_symbol_batch_feed_dict)
   1059         # Node numbers for each graph
   1060         real_length=get_graph_length([elements['mask_out']])[0] # [valid_node_number]

/data3/fancc/DEVELOP/DEVELOP.py in get_node_symbol(self, batch_feed_dict)
    918     def get_node_symbol(self, batch_feed_dict):
    919         fetch_list = [self.ops['node_symbol_prob_in']]
--> 920         result = self.sess.run(fetch_list, feed_dict=batch_feed_dict)
    921         return (result[0])
    922 

~/anaconda3/envs/DEVELOP_env3/lib/python3.7/site-packages/tensorflow/python/client/session.py in run(self, fetches, feed_dict, options, run_metadata)
    948     try:
    949       result = self._run(None, fetches, feed_dict, options_ptr,
--> 950                          run_metadata_ptr)
    951       if run_metadata:
    952         proto_data = tf_session.TF_GetBuffer(run_metadata_ptr)

~/anaconda3/envs/DEVELOP_env3/lib/python3.7/site-packages/tensorflow/python/client/session.py in _run(self, handle, fetches, feed_dict, options, run_metadata)
   1149             raise ValueError('Cannot feed value of shape %r for Tensor %r, '
   1150                              'which has shape %r' %
-> 1151                              (np_val.shape, subfeed_t.name, str(subfeed_t.get_shape())))
   1152           if not self.graph.is_feedable(subfeed_t):
   1153             raise ValueError('Tensor %s may not be fed.' % subfeed_t)

ValueError: Cannot feed value of shape (1, 3) for Tensor 'graph_model/abs_dist:0', which has shape '(?, 5)'

**Comment by ChengchengGutenTag** [comment]
It is due that I downloaded from the branch in the literature (https://github.com/oxpig/DEVELOP/) rather than the latest branch (https://github.com/fimrie/DEVELOP/). After using the latest branch, it works normally.

**Comment by fimrie** [comment]
Glad we could fix the issue and we will try to avoid this going forwards. Both branches are now fully up-to-date.
